apiVersion: v1
kind: Pod
metadata:
  name: nats-docker
spec:
  containers:
    - name: nats-docker
      image: nats:2.1.9
      args: [
            '-p',
            '4222',
            '-m',
            '8222'            
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector: 
    app: nats-docker
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222