apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-api-depl
spec:
  replicas: 1
  selector:
    matchLables:
      app: node-server-api
    template:
      metadata:
        labels:
          app: node-server-api
      spec:
        containers:
          - name: node-server-api
            image: node-server-api-img