apiVersion: v1
kind: Service
metadata:
  name: node-server-api-srv
spec:
  type: NodePort
  selector:
    qpp: node-server-api
  ports:
    - name: node-server-api
      protocol: TCP
      port: 2020
      targetPort: 2020